/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
import type * as hyperlane7683 from "./hyperlane7683";
export type { hyperlane7683 };
